spring:
  datasource:
    driver-class-name: ${rds.driver}
    username: ${rds.username}
    password: ${rds.password}
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  jwt:
    client-secret: mcs-dev-secret
  data:
    redis:
      host: localhost
      port: 6379